#!/usr/bin/env bash

if ! command -v hyprpicker >/dev/null 2>&1; then exit 1; fi

color="$(hyprpicker --format=hex --no-fancy --scale=1 --radius=80)"
# printf to ensure zero leading/trailing newlines
printf "%s" "$color" | wl-copy
