#!/usr/bin/env fish

# NOTE: Usage: Options
#   (no arg)  Capture region
#   screen    Capture full screen
#   window    Capture active window

set dir ~/Pictures/Screenshots
set arg $argv[1]
set timestamp (date +%Y-%m-%d_%H-%M-%S)

function notify
    notify-send --icon satty --app-name Satty $argv
end

if [ -n "$arg" ] # screen or window
    set app (niri msg --json focused-window | jq -r '.app_id // "unknown"')
    set file "$dir/$app\_$timestamp.png"
    niri msg action screenshot-$arg --path $file
else # region
    set file "$dir/$timestamp.png"
    set sc_area (slurp -b '#04040499' -c '#13b77aa6'; or begin
        notify 'Aborted!'
        exit 1
    end)
    grim -g $sc_area $file
    wl-copy -t image/png <$file
    notify "Screenshots saved at" (printf $file | sed "s|^$HOME|~|")
end
