# vim:ft=hyprlang

unbind = $kb_terminate_process
bind   = $kb_terminate_process, exec, $scripts/kill-active-process.sh

unbind = ALT, Tab
bind   = ALT, Tab, focuscurrentorlast
unbind = SUPER, Tab
bind   = SUPER, Tab, workspace, previous_per_monitor

bind   = SUPER SHIFT, Equal, layoutmsg, colresize +conf
bind   = SUPER SHIFT, Minus, layoutmsg, colresize -conf
