# vim:ft=hyprlang

windowrule = match:class ^(com.mitchellh.ghostty)$, opaque on
windowrule = match:title Oklch Color Picker, center on, float on, size (monitor_w*.4) (monitor_h*.5)
windowrule = match:class spotify, pseudo on, size (monitor_w*.7) (monitor_h*.75)
windowrule = match:class discord, pseudo on, size (monitor_w*.9) (monitor_h*.93)
