# vim:ft=hyprlang

## Tags ---------------------
# Browsers
windowrule = match:class ^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$, tag +browser
windowrule = match:class ^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$, tag +browser
windowrule = match:class ^(chrome-.+-Default)$, tag +browser
windowrule = match:class ^([Cc]hromium)$, tag +browser
windowrule = match:class ^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$, tag +browser
windowrule = match:class ^(Brave-browser(-beta|-dev|-unstable)?)$, tag +browser
windowrule = match:class ^([Tt]horium-browser|[Cc]achy-browser)$, tag +browser
windowrule = match:class ^(zen-alpha|zen)$, tag +browser

# Image viewer
windowrule = match:class ^(imv)$, tag +image-viewer
windowrule = match:class ^(swayimg)$, tag +image-viewer
windowrule = match:class ^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$, tag +image-viewer
windowrule = match:class ^(evince)$, tag +image-viewer
windowrule = match:class ^(eog|org.gnome.Loupe)$, tag +image-viewer

## ---------------------
windowrule = match:class ^(com.mitchellh.ghostty)$, opaque on
windowrule = match:title Oklch Color Picker, center on, float on, size (monitor_w*.4) (monitor_h*.5)
windowrule = match:class spotify, pseudo on, size (monitor_w*.7) (monitor_h*.75)
windowrule = match:class Lotion, pseudo on, size (monitor_w*.9) (monitor_h*.93) # Notion
# windowrule = match:tag browser, size (monitor_w*.9) (monitor_h*.93)

windowrule = match:tag viewer, float on, center on, opacity 0.82 0.75

# ZEN browser
windowrule = match:class zen, match:title ^(Sign in.*)$, float on, center on, size (monitor_w*.7) (monitor_h*.5)
windowrule = match:class zen, match:title Library, float on, size (monitor_w*.5) (monitor_h*.5)
