# ### Hyprland ###
# Touchpad
$touchpad_disable_typing = true
$touchpad_scroll_factor = 0.3
$ws_swipe_fingers = 4
$gesture_fingers = 3
$gesture_fingersMore = 4

# Blur
$blur_enabled = true
$blur_special_ws = false
$blur_popups = true
$blur_input_methods = true
$blur_size = 8
$blur_passes = 2
$blur_xray = false

# Shadow
$shadow_enabled = true
$shadow_range = 20
$shadow_render_power = 3
$shadow_colour = rgba($surfaced4)

# Gaps
$ws_gaps = 20
$win_gaps_in = 6
$win_gaps_out = 10
$single_win_gaps_out = 20

# Window styling
$win_opacity = 0.95
$win_rounding = 10

$win_border_size = 2
$active_win_border_color = rgba($primary66)
$inactive_win_border_color = rgba($onSurfaceVariant11)

# Misc
$volume_step = 10  # In percent
$cursor_theme = sweet-cursors
$cursor_size = 24


# ### Keybinds ###
# Workspaces
$kb_focus_win = SUPER
$kb_move_win_to_ws = CTRL SUPER
$kb_goto_ws = SUPER

$kb_next_ws = CTRL SUPER, J
$kb_prev_ws = CTRL SUPER, K

$kb_toggle_special_ws = SUPER, S

# Window groups
$kb_win_group_cycle_next = Alt, Tab
$kb_win_group_cycle_prev = SHIFT ALT, Tab
$kb_ungroup = SUPER, U
$kb_toggle_group = SUPER, Comma

# Window actions
$kb_move_win = SUPER SHIFT
$kb_resize_win = SUPER ALT
$kb_window_pip = SUPER ALT, Backslash
$kb_pin_win = SUPER, P
$kb_win_fullscreen = SUPER, F
$kb_win_bordered_fullscreen = SUPER ALT, F
$kb_toggle_win_floating = SUPER ALT, Space
$kb_close_win = SUPER, Q

# Special workspace toggles
$kb_open_system_monitor = CTRL SHIFT, Escape
$kb_open_music = SUPER, M
$kb_open_comm = SUPER, D
$kb_open_todo = SUPER, R

# Apps
$kb_open_terminal = SUPER, Return
$kb_open_browser = SUPER, W
$kb_open_file_explorer = SUPER, E

# Misc
$kb_session = SUPER, Delete
$kb_clear_notifs = CTRL ALT, C
$kb_show_panels = SUPER ALT, K
$kb_lock = SUPER ALT, L
