decoration {
    rounding = $win_rounding
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1

    blur {
        enabled = $blur_enabled
        xray = $blur_xray
        special = $blur_special_ws
        ignore_opacity = true  # Allows opacity blurring
        new_optimizations = true
        popups = $blur_popups
        input_methods = $blur_input_methods
        size = $blur_size
        passes = $blur_passes
    }

    shadow {
        enabled = $shadow_enabled
        range = $shadow_range
        render_power = $shadow_render_power
        color = $shadow_colour
    }
}
