input {
    kb_layout = us
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 0
    follow_mouse = 2

    scroll_factor = 0.6
    sensitivity = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
        clickfinger_behavior = false
        middle_button_emulation = false
        tap-to-click = true
        drag_lock = false
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
    sync_gsettings_theme = true
    no_hardware_cursors = 2 # change to 1 if want to disable
    enable_hyprcursor = true
    warp_on_change_workspace = 2
    no_warps = true
    inactive_timeout = 3  # hide after seconds
}

