return {}
-- local biome = { 'biome' }
-- local prettier = { 'prettierd' }
--
-- return {
-- 	{
-- 		'stevearc/conform.nvim',
-- 		opts = {
-- 			log_level = vim.log.levels.WARN,
-- 			notify_on_error = false,
-- 			notify_no_formatters = true,
-- 			formatters_by_ft = {
-- 				typescript = biome,
-- 				typescriptreact = biome,
-- 				javascript = biome,
-- 				javascriptreact = biome,
-- 				css = biome,
-- 				scss = biome,
-- 				sass = biome,
-- 				json = biome,
-- 				jsonc = biome,
--
-- 				markdown = prettier,
-- 				astro = prettier,
-- 				less = prettier,
-- 				yaml = prettier,
-- 				svelte = prettier,
-- 				vue = prettier,
-- 				angular = prettier,
-- 			},
-- 		},
-- 	},
-- }
