return {
	{ -- Fun Animations
		'eandrju/cellular-automaton.nvim',
		cmd = 'CellularAutomaton',
		lazy = true,
	},

	{ -- Typescript type debug
		'marilari88/twoslash-queries.nvim',
		ft = { 'typescript', 'typescriptreact', 'astro' },
		opts = {
			multi_line = true,
			is_enabled = true,
			highlight = 'Comment',
		},
	},

	{ -- Lua Type: Wezterm object
		'justinsgithub/wezterm-types',
		lazy = true,
		dependencies = { 'lazydev.nvim', opts = function(_, opts) table.insert(opts.library, { path = 'wezterm-types', mods = { 'wezterm' } }) end },
		cond = function() return vim.fn.fnamemodify(vim.fn.expand '%', ':t') == 'wezterm.lua' end,
	},

	{
		'NStefan002/screenkey.nvim',
		lazy = false,
		version = '*',
		cmd = 'Screenkey',
		opts = {
			win_opts = {
				row = vim.o.lines - vim.o.cmdheight - 1,
				col = vim.o.columns - 1,
				relative = 'editor',
				anchor = 'SE',
				width = 40,
				height = 3,
				border = 'single',
				title = 'Screenkey',
				title_pos = 'center',
				style = 'minimal',
				focusable = false,
				noautocmd = true,
			},
			compress_after = 3,
			clear_after = 3,
			disable = {
				filetypes = {},
				buftypes = {},
				events = false,
			},
			show_leader = true,
			group_mappings = false,
			display_infront = {},
			display_behind = {},
			filter = function(keys) return keys end,
			keys = {
				['<TAB>'] = '󰌒',
				['<CR>'] = '󰌑',
				['<ESC>'] = 'Esc',
				['<SPACE>'] = '␣',
				['<BS>'] = '󰌥',
				['<DEL>'] = 'Del',
				['<LEFT>'] = '',
				['<RIGHT>'] = '',
				['<UP>'] = '',
				['<DOWN>'] = '',
				['<HOME>'] = 'Home',
				['<END>'] = 'End',
				['<PAGEUP>'] = 'PgUp',
				['<PAGEDOWN>'] = 'PgDn',
				['<INSERT>'] = 'Ins',
				['<F1>'] = 'F1',
				['<F2>'] = 'F2',
				['<F3>'] = 'F3',
				['<F4>'] = 'F4',
				['<F5>'] = 'F5',
				['<F6>'] = 'F6',
				['<F7>'] = 'F7',
				['<F8>'] = 'F8',
				['<F9>'] = 'F9',
				['<F10>'] = 'F10',
				['<F11>'] = 'F11',
				['<F12>'] = 'F12',
				['CTRL'] = 'Ctrl',
				['ALT'] = 'Alt',
				['SUPER'] = '󰘳',
				['<leader>'] = '<leader>',
			},
		},
	},
}
