#!/usr/env/bin fish

begin
    string unescape $FZF_HOME_PROJECTS
    $find_cmd -a -d 1 -t d -- . $FZF_HOME_PROJECTS
end \
    | sort -ur \
    | string replace "$HOME/" '' \
    | $fzf_cmd --border-label ' Goto Work Directory ' \
    | read -l result
or return

source (type --path __fzf_open_path) ~/$result
