#!/usr/bin/env fish

begin
    string unescape $FZF_HOME_PROJECTS
    fd -HLa -td -d1 -- . $FZF_HOME_PROJECTS
end \
    | sort -ur \
    | string replace "$HOME/" '' \
    | $fzf_cmd --border-label ' Open new session ' \
    | read -l selected_path
or return 0

set selected_path (realpath ~/$selected_path)
set selected_name (basename $selected_path | tr . _)

if not contains -- $session_name (tmux list-sessions -F '#{session_name}')
    tmux new-session -c $selected_path -s $selected_name -d
end

if [ -n "$TMUX" ]
    tmux switch-client -t $selected_name
else
    tmux attach-session -t $selected_name
end
