#!/usr/bin/env fish

set path (fzf.home --print --absolute --label ' Open new session ')
or return 1
echo $path

# Set variables
set name (basename $path)

# Tmux session handling
set sessions (pgrep tmux &>/dev/null && tmux list-sessions -F '#{session_name}')
if not string match -qe -- "$name" "$sessions"
    tmux new-session -c "$path" -s "$name" -d
end

# Attach or switch to session
test -n "$TMUX"; and set action switch-client; or set action attach-session

tmux $action -t "$name"
