#!/usr/bin/env fish

# NOTE: Still an immature script.
# TODO: Add more/better logic.

# System builtin package manager
begin
    if type -q yay
        yay
    else
        sudo pacman -Syu
    end
end; or return

# Rust package manager
rustup update; or return
cargo install-update -a; or return

# NeoVim version manager
bob update nightly; or return
bob update stable; or return

# Bun
begin
    if which bun &>/dev/null
        bun upgrade
        bun update -g --latest
    end
end; or return
