[audio]
enable_overdrive = true
enable_sounds = true

[bar]
order = [ "Main" ]

    [bar.Main]
    auto_hide = true
    background_opacity = 0.7
    radius = 0
    margin_edge = 0
    margin_ends = 0
    position = "right"
    reserve_space = false
    capsule_fill = "shadow"
    capsule_opacity = 0.7
    contact_shadow = true
    capsule_groups = [ "System" ]
    start = [ "control-center", "workspaces", "media" ]
    end = [ "tray", "volume", "notifications" ]

[brightness]
enable_ddcutil = true

[dock]
active_monitor_only = true
background_opacity = 0.7
auto_hide = true
enabled = true
icon_size = 30
inactive_opacity = 0.8
inactive_scale = 1.0
pinned = [ "zen", "com.mitchellh.ghostty", "vesktop" ]
radius = 12

[nightlight]
use_weather_location = false

[notification]
layer = "top"

[shell]
password_style = "random"
polkit_agent = true
settings_show_advanced = true

[theme]
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "btop", "qt" ]
    community_ids = [ "spicetify", "steam", "zed" ]
    enable_user_templates = true

[wallpaper]
fill_color = "#000000"

[weather]
auto_locate = true

[widget.clock]
anchor = true

[widget.control-center]
capsule = true

[widget.notifications]
capsule = true
capsule_group = "System"
hide_when_no_unread = false

[widget.tray]
capsule = true
drawer = true
hidden = [ "zero-trust-client", "Easy Effects" ]

[widget.volume]
capsule = true
capsule_group = "System"
show_label = false

[widget.workspaces]
capsule = true

