[config]

[templates]

[templates.niri]
input_path="~/.config/noctalia/templates/niri.kdl"
output_path="~/.config/niri/cfg/theme.kdl"

[templates.vesktop]
input_path="~/.config/noctalia/templates/vesktop.css"
output_path="~/.config/vesktop/themes/Nihil.theme.css"

[templates.zen_userChrome]
input_path="~/.config/noctalia/templates/zen/zen-userChrome.css"
output_path="~/.cache/noctalia/zen-browser/zen-userChrome.css"
[templates.zen_userContent]
input_path="~/.config/noctalia/templates/zen/zen-userContent.css"
output_path="~/.cache/noctalia/zen-browser/zen-userContent.css"

[templates.sddm]
input_path="/usr/share/sddm/themes/noctalia/theme.template.conf"
output_path="/usr/share/sddm/themes/noctalia/theme.conf"
