theme = "Rose-pine"
client_id = "65b708073fc0480ea92a077233ca87bd"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
  {track}  {artists}  {album}
  │ {status} │ {metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = ""
pause_icon = ""
liked_icon = "│"
border_type = "Rounded" # Hidden, Plain, Rounded, Double or Thick
progress_bar_type = "Line" # Rectangle, Line
enable_media_control = true
enable_streaming = "Always"
default_device = "spotify-player"
seek_duration_secs = 3

[layout]
playback_window_position = "Bottom" # Top, Bottom
playback_window_height = 3

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = true
normalization = true
autoplay = true
