# Disable keymaps
[[keymaps]]
command = "None"
key_sequence = "q"
[[keymaps]]
command = "None"
key_sequence = "C-c"
[[keymaps]]
command = "None"
key_sequence = "l"
[[keymaps]]
command = "None"
key_sequence = "n"
[[keymaps]]
command = "None"
key_sequence = "p"

# New maps
[[keymaps]]
command = "Quit"
key_sequence = "Q Q"

[[keymaps]]
command = "ChooseSelected"
key_sequence = "l"

[[keymaps]]
command = "PreviousPage"
key_sequence = "q"

[[keymaps]]
command = { VolumeChange = { offset = 2 } }
key_sequence = "="
[[keymaps]]
command = { VolumeChange = { offset = -2 } }
key_sequence = "-"

[[keymaps]]
command = "SeekForward"
key_sequence = "right"
[[keymaps]]
command = "SeekBackward"
key_sequence = "left"

[[keymaps]]
command = "NextTrack"
key_sequence = ">"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "<"
