[[themes]]
name = "Rose-pine"
[themes.palette]
# background = "#191724"
foreground = "#E0DEF4"
black = "#1F1D2E"
blue = "#31748f"           # pine
cyan = "#9ccfd8"           # foam
green = "#ebbcba"          # rose
magenta = "#c4a7e7"        # iris
red = "#eb6f92"            # love
white = "#cdd6f4"          # text
yellow = "#f6c177"         # gold
bright_black = "#524f67"   # highligh_med
bright_blue = "#21202e"    # highligh_low
bright_cyan = "#89dceb"
bright_green = "#a6e3a1"
bright_magenta = "#cba6f7"
bright_red = "#f38ba8"
bright_white = "#cdd6f4"
bright_yellow = "#6e6a86"  # muted

[themes.component_style]
selection = { bg = "BrightBlue", modifiers = ["Bold"] }
block_title = { fg = "Cyan", modifiers = ["Bold", "Italic"] }
playback_track = { fg = "Green", modifiers = ["Bold", "Italic"] }
playback_album = { fg = "Red", modifiers = ["Bold", "Italic"] }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { fg = "Green" }
playback_progress_bar_unfilled = { fg = "BrightBlack" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = { fg = "BrightBlack" }
playback_status = { fg = "White" }
playback_artists = { fg = "Magenta", modifiers = ["Bold", "Italic"] }
playlist_desc = { fg = "Blue" }

[[themes]]
name = "Catppuccin-mocha"
[themes.palette]
# background = "#1e1e2e"
foreground = "#cdd6f4"
black = "#1e1e2e"
blue = "#89b4fa"
cyan = "#89dceb"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#cdd6f4"
yellow = "#f9e2af"
bright_black = "#1e1e2e"
bright_blue = "#89b4fa"
bright_cyan = "#89dceb"
bright_green = "#a6e3a1"
bright_magenta = "#cba6f7"
bright_red = "#f38ba8"
bright_white = "#cdd6f4"
bright_yellow = "#f9e2af"

[themes.component_style]
selection = { bg = "#313244", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { fg = "Green" }
playback_progress_bar_unfilled = { fg = "White" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#a6adc8" }
